// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: job.proto

package job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobOrder_Create_FullMethodName = "/job.JobOrder/Create"
)

// JobOrderClient is the client API for JobOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobOrderClient interface {
	Create(ctx context.Context, in *JobOrderRequest, opts ...grpc.CallOption) (*JobOrderResponse, error)
}

type jobOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewJobOrderClient(cc grpc.ClientConnInterface) JobOrderClient {
	return &jobOrderClient{cc}
}

func (c *jobOrderClient) Create(ctx context.Context, in *JobOrderRequest, opts ...grpc.CallOption) (*JobOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobOrderResponse)
	err := c.cc.Invoke(ctx, JobOrder_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobOrderServer is the server API for JobOrder service.
// All implementations must embed UnimplementedJobOrderServer
// for forward compatibility.
type JobOrderServer interface {
	Create(context.Context, *JobOrderRequest) (*JobOrderResponse, error)
	mustEmbedUnimplementedJobOrderServer()
}

// UnimplementedJobOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobOrderServer struct{}

func (UnimplementedJobOrderServer) Create(context.Context, *JobOrderRequest) (*JobOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedJobOrderServer) mustEmbedUnimplementedJobOrderServer() {}
func (UnimplementedJobOrderServer) testEmbeddedByValue()                  {}

// UnsafeJobOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobOrderServer will
// result in compilation errors.
type UnsafeJobOrderServer interface {
	mustEmbedUnimplementedJobOrderServer()
}

func RegisterJobOrderServer(s grpc.ServiceRegistrar, srv JobOrderServer) {
	// If the following call pancis, it indicates UnimplementedJobOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobOrder_ServiceDesc, srv)
}

func _JobOrder_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobOrderServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobOrder_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobOrderServer).Create(ctx, req.(*JobOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobOrder_ServiceDesc is the grpc.ServiceDesc for JobOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobOrder",
	HandlerType: (*JobOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _JobOrder_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
